\connect optimal

-- Default privileges para objetos creados por data_ingestor
-- Schema optimal
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA optimal
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA optimal
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA optimal
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA optimal
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA optimal
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema raw
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA raw
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA raw
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA raw
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA raw
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA raw
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema staging
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA staging
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA staging
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA staging
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA staging
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA staging
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema prod
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA prod
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA prod
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA prod
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA prod
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE data_ingestor IN SCHEMA prod
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Default privileges para objetos creados por optimal_backend
-- Schema optimal
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA optimal
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA optimal
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA optimal
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA optimal
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA optimal
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema raw (optimal_backend solo puede leer)
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA raw
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA raw
  GRANT SELECT ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA raw
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA raw
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA raw
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema staging (optimal_backend solo puede leer)
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA staging
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA staging
  GRANT SELECT ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA staging
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA staging
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA staging
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;

-- Schema prod (optimal_backend puede leer y escribir)
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA prod
  GRANT SELECT ON TABLES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA prod
  GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA prod
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO optimal_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA prod
  GRANT USAGE, SELECT ON SEQUENCES TO optimal_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE optimal_backend IN SCHEMA prod
  GRANT EXECUTE ON FUNCTIONS TO optimal_ro, optimal_rw;
